In [4]:
import torch

data = torch.tensor([1, 2, 3])
print(data.shape)

torch.Size([3])


In [5]:
data = torch.arange(0, 6, 0.5)
print(data)

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000, 5.5000])


In [6]:
import torch.nn as nn 

t1 = torch.Tensor([1,2,3,4])
t2 = torch.Tensor([5,5,5,5])

mse_loss = nn.MSELoss()
loss = mse_loss(t1, t2)
print(loss)

tensor(7.5000)


In [7]:
x = torch.tensor(3.0, requires_grad=True)

y = x**2
z = 3*y + 2

z.backward()
print(x.grad)

tensor(18.)


In [9]:
x = torch.tensor([6.7])
print(x)

w = -0.34
b = 0.04

y_hat = x*w + b
print(y_hat)

tensor([6.7000])
tensor([-2.2380])


In [12]:
linear_model = nn.Linear(1, 1)
print(linear_model.bias)
print(linear_model.weight)

Parameter containing:
tensor([0.3088], requires_grad=True)
Parameter containing:
tensor([[0.8641]], requires_grad=True)


In [13]:
from torchsummary import summary

model = nn.Sequential(
    nn.Linear(1, 1)
)

summary(model, input_size=(1,))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                    [-1, 1]               2
Total params: 2
Trainable params: 2
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


Output shape: [-1, 1] have -1 is number of sample, 1 is output shape

In [ ]:
loss_fn = torch.nn.MSELoss()
optimizer = torch.nn.SGD(linear_model.parameters(), lr=0.01)