In [2]:
import numpy as np

In [3]:
def df_W(W):
    w1, w2 = W[0], W[1]
    dw1 = 0.2*w1
    dw2 = 4*w2
    
    dW = np.array([dw1, dw2])
    return dW

In [4]:
def sgd(W, dW, lr):
    W = W - lr*dW
    return W

In [ ]:
def train_pl(optimizer, lr, epochs):
    W = np.array([-5, -2], dtype=np.float32)
    results = [W]
    
    for i in range(epochs):
        dW = df_W(W)
        W = optimizer(W, dW, lr)
        results.append(W)

    return results

In [6]:
train_pl(sgd, lr=0.4, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.6,  1.2]),
 array([-4.232, -0.72 ]),
 array([-3.89344,  0.432  ]),
 array([-3.5819648, -0.2592   ]),
 array([-3.29540762,  0.15552   ]),
 array([-3.03177501, -0.093312  ]),
 array([-2.78923301,  0.0559872 ]),
 array([-2.56609437, -0.03359232]),
 array([-2.36080682,  0.02015539]),
 array([-2.17194227, -0.01209324]),
 array([-1.99818689,  0.00725594]),
 array([-1.83833194, -0.00435356]),
 array([-1.69126538,  0.00261214]),
 array([-1.55596415, -0.00156728]),
 array([-1.43148702e+00,  9.40369969e-04]),
 array([-1.31696806e+00, -5.64221981e-04]),
 array([-1.21161061e+00,  3.38533189e-04]),
 array([-1.11468176e+00, -2.03119913e-04]),
 array([-1.02550722e+00,  1.21871948e-04]),
 array([-9.43466646e-01, -7.31231688e-05]),
 array([-8.67989314e-01,  4.38739013e-05]),
 array([-7.98550169e-01, -2.63243408e-05]),
 array([-7.34666155e-01,  1.57946045e-05]),
 array([-6.75892863e-01, -9.47676268e-06]),
 array([-6.21821434e-01,  5.68605761e-06]),
 array([-